flask_web/app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship("User", backref='role')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    account = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

    def generate_auth_token(self, expiration):
        s = Serializer(current_app.config['SECRET_KEY'],
                       expires_in=expiration)
        # 必须解码....
        return s.dumps({'id': self.id}).decode('ascii')

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return None
        return User.query.get(data['id'])


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

flask_web/app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_pymongo import PyMongo


bootstrap = Bootstrap()
db = SQLAlchemy()
mongo = PyMongo()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mongo.init_app(app, config_prefix='MONGO')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    return app

flask_web/app/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint("api", __name__)

from . import authentication, views, errors

flask_web/app/api_1_0/views.py
from flask import jsonify, request, abort, g, url_for, current_app, make_response
from .. import db
from .import api
from .mqttpub_bak import topic_dict, topic_dict_for_android
from .authentication import auth
from flask_login import login_required
import paho.mqtt.publish as mqttpub
from ..main.mqttsub import actuator_dict, Conversion_table, actuator_num_list
from redis import Redis
import json


r = Redis(host='localhost', port=6379, db=0)
# actuator_num_list = ['air condition/sleep time', 'air condition/temperature']


# @api.route('/sensor_data')
# def get_data_test():
#     # response = make_response(jsonify(topic_dict))
#     response = make_response(r.get('sensor_api').decode('utf-8'))
#     response.headers['Access-Control-Allow-Origin'] = '*'  # for ajax...
#     response.headers['Access-Control-Allow-Methods'] = 'POST'
#     response.headers['Access-Control-Allow-Headers'] = 'x-requested-with,content-type'
#     return response


@api.route('/sensor_data/<species>')  # use redis
@login_required
def get_test_data(species):
    temp_dict = {}
    if species in topic_dict:
        for item in topic_dict[species]:
            if item[-6:] != '_chart':
                # print(r.get(item))
                # print(type(r.get(item)))
                temp_dict[item] = r.get(item).decode('utf-8')
        # print('this is ..')
        # print(temp_dict)
    else:
        abort(404)
    return make_response(jsonify(temp_dict))


@api.route('/sensor_chart_data/<species>')
@login_required
def get_test_chart_data(species):
    temp_dict = {}
    if species in topic_dict:
        for item in topic_dict[species]:
            if item[-6:] == '_chart':
                temp_dict[item] = json.loads(r.get(item).decode('utf-8'))
        # print(temp_dict)
    else:
        abort(404)
    return make_response(jsonify(temp_dict))


@api.route('/sensor_data_for_android/<path:topic>')
def api_for_android(topic):
    for x in topic_dict_for_android:
        if topic in topic_dict_for_android[x]:
            dict_for_android = {
                topic: float(topic_dict_for_android[x][topic]),
                topic + '_chart': topic_dict_for_android[x][topic + '_chart']
            }
            response = make_response(jsonify(dict_for_android))
            response.headers['Access-Control-Allow-Origin'] = '*'  # for ajax...
            response.headers['Access-Control-Allow-Methods'] = 'POST'
            response.headers['Access-Control-Allow-Headers'] = 'x-requested-with,content-type'
            return response
    return jsonify('error.')


@api.route('/use_actuator', methods=['POST'])
@auth.login_required
def send_operating():
    # mqttpub.single(request.form.get('topic'), request.form.get('parameter'))
    content = request.get_json(force=True)  # Automatically convert to dict...
    print(content)
    # print(type(content))
    if content['topic'] in actuator_num_list:
        actuator_dict[content['topic']] = content['parameter']
    else:
        actuator_dict[content['topic']] = Conversion_table[content['parameter']]
    mqttpub.single(content['topic'], content['parameter'])
    # print(json.loads(str(content)))
    return jsonify('success')


@api.route('/get_actuator')
@auth.login_required
def get_actuator_message():
    return jsonify(actuator_dict)

flask_web/app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors

flask_web/app/main/views.py
from flask import render_template, jsonify, redirect, url_for
from flask_login import login_required
from . import main
import requests
import json

# r = requests.get('http://localhost:5001/api/v1.0/sensor_data')
# temp_data = json.loads(r.text)


# def get_api():
#     try:
#         r = requests.get('http://localhost:5001/api/v1.0/sensor_data')
#     except ConnectionError:
#         return None
#     return json.loads(r.text)


@main.route('/')
@login_required
def index():
    return redirect(url_for('main.temperature_and_humidity'))


# @main.route('/data/<data_name>')
# def data_item(data_name):
#     try:
#         # return jsonify(topic_dict[data_name])
#         # r = requests.get('http://120.25.242.228:29040')
#         # temp_data = json.loads(r.text)
#
#         # temp_data = get_api()
#         return jsonify(temp_data[data_name])
#     except KeyError:
#         return render_template('404.html'), 404
#
#
# @main.route('/data/chart/<topic_name>')
# def date_chart_item(topic_name):
#     topic_name = topic_name.replace('_', '/') + '_chart'
#     # r = requests.get('http://120.25.242.228:29040')
#     # temp_data = json.loads(r.text)
#
#     if topic_name in temp_data['chart'].keys():
#         try:
#             return jsonify(temp_data['chart'][topic_name])
#         except TypeError:
#             return jsonify(None)
#     return render_template('404.html'), 404


@main.route('/temperature_and_humidity')
@login_required
def temperature_and_humidity():
    return render_template('TemAndHum.html')


@main.route('/air_quality')
@login_required
def air_quality():
    return render_template('air_quality.html')


# 如何解决debug时的两次mqttsub执行
# 是否需要改变mqttpub的位置，让其能与mqttsub共享topic_list
# 是否要将topic_list放入config
# js时候要使用flask for语法

flask_web/app/templates/TemAndHum.html
{% extends "base_data.html" %}

{% block head %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='javascripts/jquery_ajax_TemAndHum.js') }}"></script>

<script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>

<script src="http://cdn.bootcss.com/crypto-js/3.1.9/core.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/evpkdf.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/cipher-core.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/aes.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/hmac.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/sha1.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/hmac-sha1.js"></script>
<script src="http://cdn.bootcss.com/crypto-js/3.1.9/enc-base64.js"></script>

<script type="text/javascript" src="{{ url_for('static', filename='javascripts/jsonp_callback.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='javascripts/use_weather_api.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='javascripts/Tem_use_chart_and_level.js') }}"></script>
{% endblock %}

{% block page_content %}
{{ super() }}
<h2>室内</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>温度</td>
            <td id="temperature">Please wait...</td>
        </tr>
        <tr>
            <td>等级</td>
            <td id="temperature_level">Please wait...</td>
        </tr>
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_temperature">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>湿度</td>
            <td id="humidity">Please wait...</td>
        </tr>
        <tr>
            <td>等级</td>
            <td id="humidity_level">Please wait...</td>
        </tr>
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_humidity">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<h2>室外</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>温度</td>
            <td id="outdoor-temperature">Please wait...</td>
        </tr>
        <tr>
            <td>等级</td>
            <td id="outdoor-temperature_level">Please wait...</td>
        </tr>
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_outdoor_temperature">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>湿度</td>
            <td id="outdoor-humidity">Please wait...</td>
        </tr>
        <tr>
            <td>等级</td>
            <td id="outdoor-humidity_level">Please wait...</td>
        </tr>
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_outdoor_humidity">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<h2>是否降雨</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>降雨</td>
            <td id="weather">Please wait...</td>
        </tr>
        </tbody>
    </table>
</div>
<h2>天气预报</h2>
<h3>当前天气</h3>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>温度</td>
            <td id="current_weather_temperature">Please wait...</td>
        </tr>
        <tr>
            <td>天气类型</td>
            <td id="current_weather_text">Please wait...</td>
        </tr>
        </tbody>
    </table>
</div>
<h3>未来三天天气</h3>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>日期</th>
            <th>白天天气</th>
            <th>夜间天气</th>
            <th>最高温</th>
            <th>最低温</th>
            <th>风向</th>
            <th>风方向角</th>
            <th>风速</th>
            <th>风力等级</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td id="today">Please wait...</td>
            <td id="today_text_day">Please wait...</td>
            <td id="today_text_night">Please wait...</td>
            <td id="today_high">Please wait...</td>
            <td id="today_low">Please wait...</td>
            <td id="today_wind_direction">Please wait...</td>
            <td id="today_wind_direction_degree">Please wait...</td>
            <td id="today_wind_speed">Please wait...</td>
            <td id="today_wind_scale">Please wait...</td>
        </tr>
        <tr>
            <td id="tomorrow">Please wait...</td>
            <td id="tomorrow_text_day">Please wait...</td>
            <td id="tomorrow_text_night">Please wait...</td>
            <td id="tomorrow_high">Please wait...</td>
            <td id="tomorrow_low">Please wait...</td>
            <td id="tomorrow_wind_direction">Please wait...</td>
            <td id="tomorrow_wind_direction_degree">Please wait...</td>
            <td id="tomorrow_wind_speed">Please wait...</td>
            <td id="tomorrow_wind_scale">Please wait...</td>
        </tr>
        <tr>
            <td id="after_tomorrow">Please wait...</td>
            <td id="after_tomorrow_text_day">Please wait...</td>
            <td id="after_tomorrow_text_night">Please wait...</td>
            <td id="after_tomorrow_high">Please wait...</td>
            <td id="after_tomorrow_low">Please wait...</td>
            <td id="after_tomorrow_wind_direction">Please wait...</td>
            <td id="after_tomorrow_wind_direction_degree">Please wait...</td>
            <td id="after_tomorrow_wind_speed">Please wait...</td>
            <td id="after_tomorrow_wind_scale">Please wait...</td>
        </tr>
        </tbody>
    </table>
</div>
<h3>生活指数</h3>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <th>穿衣</th>
            <th>洗车</th>
            <th>紫外线强度</th>
            <th>旅游</th>
            <th>运动</th>
            <th>感冒</th>
        </tr>
        <tr>
            <td id="dressing">Please wait...</td>
            <td id="car_washing">Please wait...</td>
            <td id="uv">Please wait...</td>
            <td id="travel">Please wait...</td>
            <td id="sport">Please wait...</td>
            <td id="flu">Please wait...</td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

flask_web/app/templates/actuator.html
{% extends "base_data.html" %}

{% block head %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='javascripts/jquery_ajax_actuator.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='javascripts/use_actuator.js') }}"></script>
{% endblock %}

{% block page_content %}
{{ super() }}
<h2>空气净化器</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>开关</td>
            <td id="air_text"></td>
        </tr>
        <!--<tr>-->
            <!--<td>等级</td>-->
            <!--<td id="air_cleaner_level"></td>-->
        <!--</tr>-->
        </tbody>
    </table>
</div>
<div>
<div>
    <h3>开关</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_open()">开启</button>
    <button type="button" class="btn btn-primary" onclick="func_air_off()">关闭</button>
</div>
<!--<div>-->
    <!--<h3>等级</h3>-->
    <!--<button type="button" class="btn btn-primary" onclick="func_air_cleaner_mute()">静音</button>-->
    <!--<button type="button" class="btn btn-primary" onclick="func_air_cleaner_balanced()">均衡</button>-->
    <!--<button type="button" class="btn btn-primary" onclick="func_air_cleaner_performance()">性能</button>-->
<!--</div>-->
</div>
<h2>空调执行器</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>开关</th>
            <th>模式</th>
            <th>温度(℃)</th>
            <th>风速</th>
            <th>睡眠</th>
            <th>睡眠时间(h)</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td id="air_switch_text"></td>
            <td id="air_mode_text"></td>
            <td id="air_temperature_text"></td>
            <td id="air_wind_text"></td>
            <td id="air_sleep_text"></td>
            <td id="air_sleep_time_text"></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>扫风</th>
            <th>超强</th>
            <th>灯光</th>
            <th>健康</th>
            <th>干燥/辅热</th>
            <th>数显</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td id="air_sweep_text"></td>
            <td id="air_super_text"></td>
            <td id="air_light_text"></td>
            <td id="air_health_text"></td>
            <td id="air_dry_and_heat_text"></td>
            <td id="air_display_text"></td>
        </tr>
        </tbody>
    </table>
</div>
<div>
    <h3>开关</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_switch_on()">开启</button>
    <button type="button" class="btn btn-primary" onclick="func_air_switch_off()">关闭</button>
</div>
<div>
    <h3>模式</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_mode_fan()">换风</button>
    <button type="button" class="btn btn-primary" onclick="func_air_mode_auto()">自动</button>
    <button type="button" class="btn btn-primary" onclick="func_air_mode_dry()">除湿</button>
    <button type="button" class="btn btn-primary" onclick="func_air_mode_heat()">制热</button>
    <button type="button" class="btn btn-primary" onclick="func_air_mode_cool()">制冷</button>
</div>
<h3>温度（摄氏度）</h3>
<div class="row">
    <div class="col-md-2">
        <input id="temperature" type="text" class="form-control">
    </div>
    <div class="col-md-1">
        <button type="button" class="btn btn-primary" onclick="func_submit_temperature()">提交</button>
    </div>
</div>
<div>
    <h3>风速</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_wind_zero()">自动</button>
    <button type="button" class="btn btn-primary" onclick="func_air_wind_low()">一级</button>
    <button type="button" class="btn btn-primary" onclick="func_air_wind_middle()">二级</button>
    <button type="button" class="btn btn-primary" onclick="func_air_wind_high()">三级</button>
</div>
<div>
    <h3>扫风</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_sweep_seesaw()">上下</button>
    <button type="button" class="btn btn-primary" onclick="func_air_sweep_around()">左右</button>
    <button type="button" class="btn btn-primary" onclick="func_air_sweep_all()">上下左右</button>
    <button type="button" class="btn btn-primary" onclick="func_air_sweep_none()">关闭</button>
</div>
<div>
    <h3>睡眠</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_sleep_sleep()">打开</button>
    <button type="button" class="btn btn-primary" onclick="func_air_sleep_wake()">关闭</button>
</div>
<h3>睡眠时间（小时）</h3>
<div class="row">
    <div class="col-md-2">
        <input id="sleep_time" type="text" class="form-control">
    </div>
    <div class="col-md-1">
        <button type="button" class="btn btn-primary" onclick="func_submit_sleep_time()">提交</button>
    </div>
</div>
<div>
    <h3>超强</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_super_on()">开启</button>
    <button type="button" class="btn btn-primary" onclick="func_air_super_off()">关闭</button>
</div>
<div>
    <h3>灯光</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_light_on()">开启</button>
    <button type="button" class="btn btn-primary" onclick="func_air_light_off()">关闭</button>
</div>
<div>
    <h3>健康</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_health_health()">健康</button>
    <button type="button" class="btn btn-primary" onclick="func_air_health_ventilate()">换气</button>
    <button type="button" class="btn btn-primary" onclick="func_air_health_all()">健康+换气</button>
    <button type="button" class="btn btn-primary" onclick="func_air_health_none()">关闭</button>
</div>
<div>
    <h3>干燥/辅热</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_dry_and_heat_on()">开启</button>
    <button type="button" class="btn btn-primary" onclick="func_air_dry_and_heat_off()">关闭</button>
</div>
<div>
    <h3>数显</h3>
    <button type="button" class="btn btn-primary" onclick="func_air_display_set()">设定温度</button>
    <!--<button type="button" class="btn btn-primary" onclick="func_air_display_off()">关闭</button>-->
    <button type="button" class="btn btn-primary" onclick="func_air_display_indoor()">室内温度</button>
    <!--<button type="button" class="btn btn-primary" onclick="func_air_display_outdoor()">室外温度</button>-->
</div>

{% endblock %}

flask_web/app/templates/air_quality.html
{% extends "base_data.html" %}

{% block head %}
{{ super() }}
<script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>

<script type="text/javascript" src="{{ url_for('static', filename='javascripts/jquery_ajax_air_quality.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='javascripts/air_use_chart.js') }}"></script>
{% endblock %}

{% block page_content %}
{{ super() }}
<h2>室内</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>PM2.5</td>
            <td id="PM25">Please wait...</td>
        </tr>
        <!--<tr>-->
            <!--<td>等级</td>-->
            <!--<td>Please wait...</td>-->
        <!--</tr>-->
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_PM25">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>TVOC</td>
            <td id="TVOC">Please wait...</td>
        </tr>
        <!--<tr>-->
            <!--<td>等级</td>-->
            <!--<td>Please wait...</td>-->
        <!--</tr>-->
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_TVOC">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>CO2</td>
            <td id="CO2">Please wait...</td>
        </tr>
        <!--<tr>-->
            <!--<td>等级</td>-->
            <!--<td>Please wait...</td>-->
        <!--</tr>-->
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_CO2">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>CH2O</td>
            <td id="CH2O">Please wait...</td>
        </tr>
        <!--<tr>-->
            <!--<td>等级</td>-->
            <!--<td>Please wait...</td>-->
        <!--</tr>-->
        <tr>
            <td>走势</td>
            <td>
                <div style="height:400px;width:1000px" id="container_CH2O">Please wait...</div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

flask_web/app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block title %}活动室监测{% endblock %}

{% block head %}
{{ super() }}
<script src="http://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">SACC213</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.temperature_and_humidity') }}">温湿度</a></li>
                <li><a href="{{ url_for('main.air_quality') }}">空气质量</a></li>
                <li><a href="{{ url_for('auth.actuator') }}">执行器</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

flask_web/app/templates/base_data.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>
        Hello
        {% if current_user.is_authenticated %}
            {{ current_user.username }}
        {% else %}
            Master
        {% endif %}
    </h1>
</div>
{% endblock %}